targets:
  $default:
    builders:
      go_router_builder:
        generate_for:
          include:
            - lib/utils/router.dart

      riverpod_generator:
        generate_for:
          include:
            - lib/providers/*

      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/models/*

      freezed:
        generate_for:
          include:
            - lib/models/*

      isar_community_generator:
        generate_for:
          include:
            - lib/models/dto/*
