name: parmosys_flutter
description: "Flutter App for Project Parmosys"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

isar_version: &isar_version 3.1.8

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^15.0.0
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  firebase_core: ^3.13.0
  flutter_carousel_widget: ^3.1.0
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  go_router: ^14.8.1
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  sprintf: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  device_preview_screenshot: ^1.0.0
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

dependency_overrides:
  # Remove once appwrite is updated
  # https://appwrite.io/threads/1334415894394306571
  flutter_web_auth_2: 4.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
