name: parmosys_flutter
description: "Flutter App for Project Parmosys"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

isar_version: &isar_version 3.3.0-dev.2

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^19.0.0
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  firebase_core: ^4.1.0
  flutter_carousel_widget: ^3.1.0
  flutter_riverpod: ^3.0.0
  freezed: ^3.2.3
  go_router: ^16.2.2
  isar_community:
    version: *isar_version
  isar_community_flutter_libs:
    version: *isar_version
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.1 # update after appwrite is updated
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  sprintf: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.8.0
  custom_lint: ^0.8.0
  device_preview_screenshot: ^1.0.0
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^6.0.0
  isar_community_generator:
    version: *isar_version
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

dependency_overrides:
  build: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
